version: "3.8"
services:
        web:
          image: php_app
          ports:
            - "8001:80"
          depends_on:
            - mysql_app
        mysql_app:
          image: mysql_app:latest
          volumes:
          - db_data:/var/lib/mysql
          environment:
                MYSQL_ROOT_PASSWORD: password
                MYSQL_DATABASE: mydatabase
volumes:
    db_data: {}

